local_backend: true

backend:
  name: test-repo

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/content/projects"
    create: true

    fields:
      - { label: "Project Name", name: "title", widget: "string" }

      - { label: "Description", name: "description", widget: "text" }

      - { label: "Cover Image", name: "coverImage", widget: "image" }

      - label: "Gallery Images"
        name: "gallery"
        widget: "list"
        field:
          label: Image
          name: image
          widget: image