backend:
  name: github
  repo: HarshBhimani312002/First_Live_Project
  branch: master

media_folder: "frontend/public/uploads"
public_folder: "/uploads"

collections:
  - name: "projects"
    label: "Projects"
    folder: "frontend/src/content/projects"
    create: true
    slug: "{{slug}}"

    fields:
      - { label: "Project Name", name: "title", widget: "string" }

      - { label: "Description", name: "description", widget: "text" }

      - { label: "Cover Image", name: "coverImage", widget: "image" }

      - label: "Gallery Images"
        name: "gallery"
        widget: "list"
        field:
          label: Image
          name: image
          widget: image